# Generated by Django 4.2.7 on 2024-02-27 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(blank=True, max_length=30, null=True)),
                ('Phone', models.CharField(blank=True, max_length=12, null=True)),
                ('Address', models.CharField(blank=True, max_length=100, null=True)),
                ('Location', models.CharField(blank=True, max_length=30, null=True)),
                ('Pickup_Point', models.CharField(blank=True, max_length=30, null=True)),
                ('Drop_Point', models.CharField(blank=True, max_length=30, null=True)),
                ('Medical_History', models.CharField(blank=True, max_length=30, null=True)),
                ('Alleries', models.CharField(blank=True, max_length=30, null=True)),
                ('Special_Attention', models.CharField(blank=True, max_length=30, null=True)),
                ('Emergency_Procedures', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
