# Generated by Django 4.2.7 on 2024-03-01 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CareApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='Name',
            new_name='First_Name',
        ),
        migrations.AddField(
            model_name='registration',
            name='Kid_Image',
            field=models.ImageField(blank=True, null=True, upload_to='Children Photos'),
        ),
        migrations.AddField(
            model_name='registration',
            name='Last_Name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='Parents_Name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
