# Generated by Django 4.2.7 on 2024-03-02 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CareApp', '0002_rename_name_registration_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicles',
            fields=[
                ('Vehicle_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Vehicle_Num', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('Model', models.CharField(blank=True, max_length=50, null=True)),
                ('Color', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
