# Generated by Django 5.0.2 on 2024-03-05 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CareApp', '0003_vehicles'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vehicles',
        ),
    ]
