# Generated by Django 5.0.2 on 2024-03-11 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CareApp', '0004_delete_vehicles'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Registration',
            new_name='RegistrationDB',
        ),
    ]
