# Generated by Django 4.2.7 on 2024-03-14 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminSide', '0009_staffdb_leave_message'),
        ('CareApp', '0005_rename_registration_registrationdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationdb',
            name='Mail',
            field=models.EmailField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='registrationdb',
            name='Password',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='registrationdb',
            name='Username',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='registrationdb',
            name='date_field',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registrationdb',
            name='driver',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='AdminSide.driverdb'),
        ),
        migrations.AddField(
            model_name='registrationdb',
            name='time_field',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
