# Generated by Django 5.0.2 on 2024-03-20 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CareApp', '0007_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationdb',
            name='Is_Seen',
            field=models.CharField(blank=True, choices=[('Seen', 'Seen'), ('Not_Seen', 'Not_Seen')], default='Not_Seen', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='registrationdb',
            name='Temp_Drop_Point',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='registrationdb',
            name='Temp_Pickup_Point',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
