# Generated by Django 5.0.2 on 2024-03-20 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CareApp', '0008_registrationdb_is_seen_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationdb',
            name='Is_Seen',
        ),
    ]
