# Generated by Django 5.0.2 on 2024-03-29 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CareApp', '0009_remove_registrationdb_is_seen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CardHolder_Name', models.CharField(blank=True, max_length=900, null=True)),
                ('Card_Num', models.CharField(blank=True, max_length=50, null=True)),
                ('Amount', models.CharField(blank=True, max_length=90, null=True)),
                ('Expiry_Date', models.CharField(blank=True, max_length=50, null=True)),
                ('CVV', models.CharField(blank=True, max_length=10, null=True)),
                ('Customer_ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CareApp.registrationdb')),
            ],
        ),
    ]
