# Generated by Django 5.0.2 on 2024-03-29 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CareApp', '0010_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='Payment_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
