# Generated by Django 5.0.2 on 2024-03-29 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CareApp', '0011_payment_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='Customer_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CareApp.registrationdb'),
        ),
    ]
