# Generated by Django 5.0.2 on 2024-03-29 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminSide', '0012_alter_driverdb_vehicle_num'),
        ('CareApp', '0014_alter_payment_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='Plan_ID',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='AdminSide.plans'),
        ),
    ]
