# Generated by Django 5.0.2 on 2024-03-05 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicles',
            fields=[
                ('Vehicle_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Vehicle_Num', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('Model', models.CharField(blank=True, max_length=50, null=True)),
                ('Color', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
