# Generated by Django 5.0.2 on 2024-03-06 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminSide', '0003_alter_driverdb_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverdb',
            name='Verified',
            field=models.CharField(blank=True, choices=[('not_verified', 'Not Verified'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='NOT_VERIFIED', max_length=100, null=True),
        ),
    ]
