# Generated by Django 5.0.2 on 2024-03-07 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminSide', '0004_alter_driverdb_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverdb',
            name='Verified',
            field=models.CharField(blank=True, choices=[('NOT_VERIFIED', 'Not Verified'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='Not Verified', max_length=100, null=True),
        ),
    ]
