# Generated by Django 5.0.2 on 2024-03-11 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminSide', '0005_alter_driverdb_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Staff_Name', models.CharField(blank=True, max_length=60, null=True)),
                ('Location', models.CharField(blank=True, max_length=60, null=True)),
                ('Phone', models.CharField(blank=True, max_length=20, null=True)),
                ('Address', models.CharField(blank=True, max_length=90, null=True)),
                ('Is_Verified', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='driverdb',
            name='Vehicle_Num',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
