# Generated by Django 5.0.2 on 2024-03-11 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminSide', '0006_staffdb_driverdb_vehicle_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Plan_Name', models.CharField(blank=True, max_length=20, null=True)),
                ('Age_Group', models.CharField(blank=True, max_length=20, null=True)),
                ('Price', models.IntegerField()),
                ('Plan_Description', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
