# Generated by Django 5.0.2 on 2024-03-13 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminSide', '0007_plans'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffdb',
            name='Password',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
