# Generated by Django 5.0.2 on 2024-03-19 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminSide', '0009_staffdb_leave_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverdb',
            name='Vehicle_Num',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
